### ISSUE TITLE
Need much clearer instructions about what needs to be done for torch>=2.0.0

### ISSUE THREAD

**Issue by phalexo** [deep-floyd/IF#57]
This is not clear.
"
If you are using `torch>=2.0.0`, make sure to **delete all** `enable_xformers_memory_efficient_attention()`
functions.
"

**Comment by phalexo** [comment]
I can see only a single call to this function. Should that call be commented out?

**Comment by minskicat** [comment]
There are 3, one per stage. There is an embedded comment that says to remove this line

**Comment by phalexo** [comment]
> There are 3, one per stage. There is an embedded comment that says to remove this line

Hm. I grepped for it, saw only one. Do you know which files?

**Comment by kanttouchthis** [comment]
> > There are 3, one per stage. There is an embedded comment that says to remove this line
> 
> Hm. I grepped for it, saw only one. Do you know which files?

You dont need to change anything in the repo. You just need to change it in the code you actually use to run it, like the examples in the readme or the notebooks

**Comment by SpaceCowboy850** [comment]
It would just be nice to update to pytorch 2.0 generally, as the base pytorch instructions don't even have 1.13 (I'm sure we can easily find it), and if we don't install manually and just pip install deepfloyd 1.2-rc0, we get a CPU version of torch 1.13, so then that needs to be updated to GPU, but then because it's pip, you can start accidentally screwing up requirements for torchvision and other modules.
